#!/usr/bin/env bash
# Father scenario — memory phase.
# See investigations/father/investigation_notebook.md for the human-readable
# explanation of each step. This script only executes; it does not narrate.
set -euo pipefail

RUN_ID="${1:-${RUN_ID:-}}"
: "${RUN_ID:?Usage: $0 RUN_ID   (or RUN_ID=... $0)}"

RUNDIR="shared/experiments/${RUN_ID}"
MANIFEST="${RUNDIR}/manifest.json"
MEM_RAW="${RUNDIR}/dumps/memory/mem.raw"
ISF_DIR="shared/isf"

for f in "$MANIFEST" "$MEM_RAW"; do
  [[ -f "$f" ]] || { echo "STOP: missing required input: $f" >&2; exit 1; }
done
[[ -d "$ISF_DIR" ]] || { echo "STOP: missing ISF directory: $ISF_DIR" >&2; exit 1; }

VOL_BIN="${VOL_BIN:-vol3}"
command -v "$VOL_BIN" >/dev/null 2>&1 || { echo "STOP: '$VOL_BIN' not found on PATH" >&2; exit 1; }

DERIVED="shared/investigations/${RUN_ID}/derived/memory"
RAW="${DERIVED}/raw"
LOGDIR="shared/investigations/${RUN_ID}/logs"
mkdir -p "$RAW" "$LOGDIR"

# ISF layout convention (orchestrator/forensics/vol_runner.py):
#   <isf_dir>/<distro_family>_<kernel_release>.json
DISTRO_ID=$(jq -r '.platform.distro_id' "$MANIFEST")
KERNEL=$(jq -r '.platform.kernel' "$MANIFEST")
FAMILY="${DISTRO_ID%%-*}"

ISF_MATCH="${ISF_DIR}/${FAMILY}_${KERNEL}.json"
if [[ ! -f "$ISF_MATCH" ]]; then
  echo "[memory] no exact ISF match for ${FAMILY}_${KERNEL}.json; falling back to latest ${FAMILY}_*.json" >&2
  ISF_MATCH=$(ls -1 "${ISF_DIR}/${FAMILY}"_*.json 2>/dev/null | sort | tail -1 || true)
  [[ -n "$ISF_MATCH" ]] || { echo "STOP: no ISF symbol file found for family '$FAMILY' in $ISF_DIR" >&2; exit 1; }
fi
echo "[memory] using ISF: $ISF_MATCH"

CMDLOG="${LOGDIR}/memory-commands.log"
: > "$CMDLOG"

# vol3 selects -s by directory, not by file, and matches the ISF to the
# image's own kernel banner internally.
run_plugin() {
  local plugin="$1" out="$2"
  echo "+ $VOL_BIN -f $MEM_RAW -s $ISF_DIR -r json $plugin" >> "$CMDLOG"
  if "$VOL_BIN" -f "$MEM_RAW" -s "$ISF_DIR" -r json "$plugin" > "$out" 2> "${out%.json}.stderr.txt"; then
    echo "[memory] $plugin: ok" >&2
    echo "ok"
  else
    echo "[memory] $plugin: FAILED (see ${out%.json}.stderr.txt)" >&2
    echo "failed"
  fi
}

declare -A PLUGIN_STATUS
PLUGIN_STATUS["linux.proc.Maps"]=$(run_plugin "linux.proc.Maps" "${RAW}/proc-maps.json")
PLUGIN_STATUS["linux.pslist"]=$(run_plugin "linux.pslist" "${RAW}/pslist.json")
PLUGIN_STATUS["linux.pstree"]=$(run_plugin "linux.pstree" "${RAW}/pstree.json")
PLUGIN_STATUS["linux.psaux"]=$(run_plugin "linux.psaux" "${RAW}/psaux.json")
PLUGIN_STATUS["linux.sockstat"]=$(run_plugin "linux.sockstat" "${RAW}/sockstat.json")
PLUGIN_STATUS["linux.bash"]=$(run_plugin "linux.bash" "${RAW}/bash.json")

echo "[memory] writing findings.json"
python3 "$(dirname "$0")/metrics/memory_metrics.py" --write-findings "$RUN_ID" "$DERIVED" "$ISF_MATCH" \
  "${PLUGIN_STATUS[linux.proc.Maps]}" "${PLUGIN_STATUS[linux.pslist]}" \
  "${PLUGIN_STATUS[linux.pstree]}" "${PLUGIN_STATUS[linux.psaux]}" \
  "${PLUGIN_STATUS[linux.sockstat]}" "${PLUGIN_STATUS[linux.bash]}"

echo "[memory] writing investigation-summary.md"
python3 - "$RUN_ID" "$DERIVED" <<'PY'
import json, sys, pathlib

run_id, derived = sys.argv[1], pathlib.Path(sys.argv[2])
findings = json.loads((derived / "findings.json").read_text())

lines = [
    f"# Memory phase — {run_id}",
    "",
    "Generated by `investigations/father/runme_memory.sh`. Raw Volatility 3",
    f"plugin output is under `{derived}/raw/`. See",
    "`investigations/father/investigation_notebook.md` for what each plugin",
    "does and does not establish on its own.",
    "",
    "## Plugin run status",
    "",
]
for plugin, info in findings["plugins"].items():
    lines.append(f"- `{plugin}`: {info['status']} ({info['row_count']} row(s))")

lines += [
    "",
    "## Observations",
    "",
    "These are observations from individual plugin output, not conclusions.",
    "A plugin producing a row does not by itself prove a finding; each item",
    "below still requires human interpretation against the disk and timeline",
    "phases.",
    "",
]
for note in findings.get("observations", []):
    lines.append(f"- {note}")

lines += [
    "",
    "## Limitations",
    "",
    "- Offline analysis only; no live introspection of the source VM.",
    "- ISF must match the imaged kernel exactly or `vol3`'s internal banner",
    "  match will fail; see `findings.json.isf_path` for the file actually",
    "  used in this run.",
    "- A plugin marked `failed` above produced no rows for this run; treat",
    "  its metrics as `unknown`, not `absent`.",
    "",
]
(derived / "investigation-summary.md").write_text("\n".join(lines) + "\n")
print(f"wrote {derived}/investigation-summary.md")
PY

echo "[memory] computing metrics.json"
python3 "$(dirname "$0")/metrics/memory_metrics.py" "$RUN_ID" "$DERIVED" "$MANIFEST"

echo "[memory] done: $DERIVED"
