#!/usr/bin/env bash
# Father scenario — timeline phase.
# See investigations/father/investigation_notebook.md for the human-readable
# explanation of each step. This script only executes; it does not narrate.
#
# Uses the project's own Plaso wrapper (orchestrator/forensics/plaso_runner.py)
# rather than calling log2timeline/psort with hand-typed flags, so extraction
# always matches the project's declared targeted-collection bound
# (default_linux_filter()).
set -euo pipefail

RUN_ID="${1:-${RUN_ID:-}}"
: "${RUN_ID:?Usage: $0 RUN_ID   (or RUN_ID=... $0)}"

RUNDIR="shared/experiments/${RUN_ID}"
MANIFEST="${RUNDIR}/manifest.json"
DISK_E01="${RUNDIR}/dumps/disk/evidence_disk.E01"

for f in "$MANIFEST" "$DISK_E01"; do
  [[ -f "$f" ]] || { echo "STOP: missing required input: $f" >&2; exit 1; }
done

command -v psort >/dev/null 2>&1 || { echo "STOP: 'psort' not found on PATH" >&2; exit 1; }
command -v log2timeline >/dev/null 2>&1 || { echo "STOP: 'log2timeline' not found on PATH" >&2; exit 1; }

DERIVED="shared/investigations/${RUN_ID}/derived/timeline"
RAW="${DERIVED}/raw"
mkdir -p "$RAW"

STORAGE="${DERIVED}/timeline.plaso"

echo "[timeline] extraction (project plaso_runner, curated filter)"
if [[ ! -s "$STORAGE" ]]; then
  python3 - "$DISK_E01" "$STORAGE" <<'PY'
import sys
from pathlib import Path
from orchestrator.forensics.plaso_runner import run_log2timeline, default_linux_filter

disk_path, storage_path = Path(sys.argv[1]), Path(sys.argv[2])
run_log2timeline(
    disk_path=disk_path,
    storage_path=storage_path,
    file_filter=default_linux_filter(),
)
PY
else
  echo "[timeline] reusing existing $STORAGE"
fi

echo "[timeline] scenario-window bounded query"
# Bound the query to this run's own scenario window (manifest timestamps),
# rounded outward to whole seconds — never a literal timestamp from another
# run.
read -r WINDOW_START WINDOW_END < <(python3 - "$MANIFEST" <<'PY'
import json, sys
from datetime import datetime, timedelta, timezone

manifest = json.load(open(sys.argv[1]))
started = datetime.fromisoformat(manifest["timestamps"]["scenario_started_at"].replace("Z", "+00:00"))
ended = datetime.fromisoformat(manifest["timestamps"]["scenario_ended_at"].replace("Z", "+00:00"))
start = started.replace(microsecond=0)
end = (ended.replace(microsecond=0) + timedelta(seconds=1))
print(start.isoformat().replace("+00:00", "+00:00"), end.isoformat().replace("+00:00", "+00:00"))
PY
)
echo "[timeline] window: $WINDOW_START .. $WINDOW_END"

WINDOW_JSONL="${RAW}/window-events.jsonl"
psort -q --status_view none --output_time_zone UTC -o json_line -w "$WINDOW_JSONL" "$STORAGE" \
  "timestamp >= DATETIME('${WINDOW_START}') and timestamp < DATETIME('${WINDOW_END}')"

echo "[timeline] event-family breakdown"
jq -r '.data_type' "$WINDOW_JSONL" | sort | uniq -c | sort -rn > "${RAW}/event-family-counts.txt"

echo "[timeline] persistence-inode ordering (optional, needs disk findings.json)"
DISK_FINDINGS="shared/investigations/${RUN_ID}/derived/disk/findings.json"
INODE_JSONL="${RAW}/persistence-inode-events.jsonl"
if [[ -f "$DISK_FINDINGS" ]]; then
  PRELOAD_INODE=$(jq -r '.preload.inode // empty' "$DISK_FINDINGS")
  LIB_INODE=$(jq -r '.library.inode // empty' "$DISK_FINDINGS")
  if [[ -n "$PRELOAD_INODE" && -n "$LIB_INODE" ]]; then
    psort -q --status_view none --output_time_zone UTC -o json_line -w "$INODE_JSONL" "$STORAGE" \
      "inode == ${PRELOAD_INODE} or inode == ${LIB_INODE}"
  else
    echo "[timeline] disk findings.json present but missing inode numbers; skipping" | tee "${RAW}/persistence-inode-events.SKIPPED.txt" >&2
  fi
else
  echo "[timeline] no disk findings.json for this run yet; skipping inode-ordering query (run runme_disk.sh first)" \
    | tee "${RAW}/persistence-inode-events.SKIPPED.txt" >&2
fi

echo "[timeline] writing findings.json"
python3 "$(dirname "$0")/metrics/timeline_metrics.py" --write-findings "$RUN_ID" "$DERIVED" "$WINDOW_START" "$WINDOW_END"

echo "[timeline] writing investigation-summary.md"
python3 - "$RUN_ID" "$DERIVED" <<'PY'
import json, sys, pathlib

run_id, derived = sys.argv[1], pathlib.Path(sys.argv[2])
findings = json.loads((derived / "findings.json").read_text())

lines = [
    f"# Timeline phase — {run_id}",
    "",
    "Generated by `investigations/father/runme_timeline.sh` using the",
    "project's Plaso wrapper (`orchestrator/forensics/plaso_runner.py`) and",
    "its curated `linux_common.yaml` filter. Raw query output is under",
    f"`{derived}/raw/`.",
    "",
    f"## Bounded scenario window: {findings['window_start']} .. {findings['window_end']}",
    "",
    f"- Events in window: {findings['window_event_count']}",
    "- Event families: " + ", ".join(
        f"{k}={v}" for k, v in findings["event_family_counts"].items()
    ) if findings["event_family_counts"] else "- Event families: (none)",
    "",
    "## Persistence-inode ordering",
    "",
]
if findings.get("inode_query_run"):
    lines.append(f"- Events tied to preload/library inodes: {findings['inode_event_count']}")
else:
    lines.append(
        "- Not run: " + findings.get("inode_query_skip_reason", "no reason recorded")
    )

lines += [
    "",
    "## Limitations",
    "",
    "- Ordering conclusions from filesystem MAC times and journal/syslog",
    "  entries require human interpretation; a surviving inode's own MAC",
    "  time can postdate the activity that produced it (self-heal/rewrite",
    "  behavior) — do not read MAC time alone as activation order.",
    "- The curated filter (`linux_common.yaml`) bounds collection to likely",
    "  evidence paths; this script does not run the unfiltered control",
    "  extraction used in the historical reference notebook (out of scope",
    "  for this refactor — see the investigation notebook's TODO).",
    "- distro/journal availability is distro-specific: `systemd_journal` and",
    "  `syslog_traditional` parsers assume a systemd-journald + rsyslog",
    "  Ubuntu image; a different distro's log layout would need a different",
    "  parser set, not covered here.",
    "",
]
(derived / "investigation-summary.md").write_text("\n".join(lines) + "\n")
print(f"wrote {derived}/investigation-summary.md")
PY

echo "[timeline] computing metrics.json"
python3 "$(dirname "$0")/metrics/timeline_metrics.py" "$RUN_ID" "$DERIVED"

echo "[timeline] done: $DERIVED"
